{{- if index .Values "appflowy-web" "enabled" }}
{{- $web := index .Values "appflowy-web" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appflowy.web.fullname" . }}
  labels:
    {{- include "appflowy.labels" . | nindent 4 }}
    app.kubernetes.io/component: appflowy-web
spec:
  replicas: {{ $web.replicaCount }}
  selector:
    matchLabels:
      {{- include "appflowy.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: appflowy-web
  template:
    metadata:
      {{- with $web.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "appflowy.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: appflowy-web
    spec:
      {{- include "appflowy.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "appflowy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: appflowy-web
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: {{ include "appflowy.image" (dict "Values" .Values "image" $web.image) | quote }}
          imagePullPolicy: {{ $web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: APPFLOWY_BASE_URL
              value: {{ include "appflowy.baseUrl" . | quote }}
            - name: APPFLOWY_GOTRUE_BASE_URL
              value: {{ include "appflowy.gotrue.externalUrl" . | quote }}
            - name: APPFLOWY_WS_BASE_URL
              value: {{ include "appflowy.websocketUrl" . | quote }}
          {{- if ne (index $web "livenessProbe") false }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          {{- end }}
          {{- if ne (index $web "readinessProbe") false }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          {{- end }}
          resources:
            {{- toYaml $web.resources | nindent 12 }}
      {{- with $web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
