{{- if index .Values "appflowy-web" "enabled" }}
{{- $web := index .Values "appflowy-web" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "appflowy.web.fullname" . }}
  labels:
    {{- include "appflowy.labels" . | nindent 4 }}
    app.kubernetes.io/component: appflowy-web
spec:
  type: {{ $web.service.type }}
  ports:
    - port: {{ $web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "appflowy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: appflowy-web
{{- end }}
