{{- if .Values.gotrue.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "appflowy.gotrue.fullname" . }}
  labels:
    {{- include "appflowy.labels" . | nindent 4 }}
    app.kubernetes.io/component: gotrue
spec:
  type: {{ .Values.gotrue.service.type }}
  ports:
    - port: {{ .Values.gotrue.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "appflowy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gotrue
{{- end }}
