{{- if index .Values "appflowy-cloud" "enabled" }}
{{- $cloud := index .Values "appflowy-cloud" }}
{{- if $cloud.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "appflowy.cloud.fullname" . }}
  labels:
    {{- include "appflowy.labels" . | nindent 4 }}
    app.kubernetes.io/component: appflowy-cloud
spec:
  minAvailable: {{ $cloud.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "appflowy.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: appflowy-cloud
{{- end }}
{{- end }}
